# Generated by Django 6.1 on 2026-09-15 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item_desejado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to='catalogo.item')),
                ('item_ofertado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_enviadas', to='catalogo.item')),
                ('proponente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_feitas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'propostas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
