# Generated by Django 6.1 on 2026-09-29 02:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trocas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comentario', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('avaliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='trocas.proposta')),
            ],
            options={
                'verbose_name_plural': 'avaliações',
                'ordering': ['-criado_em'],
                'constraints': [models.UniqueConstraint(fields=('proposta', 'avaliador'), name='uma_avaliacao_por_pessoa_por_troca')],
            },
        ),
    ]
